config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :posts
  resources :properties

  get '/blog' => 'posts#latest', as: :blog

  get '/accounts' => 'admin#accounts', as: :accounts

  get '/dashboard' => 'dashboard#index', as: :dashboard
  get '/profile/:id' => 'dashboard#profile', as: :profile
  post '/agent/contact' => 'properties#email_agent', as: :email_agent

  root 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
  <%= link_to accounts_path, class: "nav-link" do %>
  <i data-feather="home"></i>
    Accounts <span class="sr-only">(current)</span>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <i data-feather="package"></i>
    Properties
  <% end %>
</li>
<li class="nav-item">
  <%= link_to posts_path, class: "nav-link" do %>
    <i data-feather="calendar"></i>
    Blog Posts
  <% end %>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="users"></i>
    Adverts
  </a>
</li>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Property</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Property</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          <% else %>
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Latest</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", blog_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Advertising</a>
        </li>
      </ul>

      <% if account_signed_in? %>
          <%= link_to 'Log Out', destroy_account_session_path, method: :delete, class: "btn btn-success float-sm-right" %>
      <% else %>
          <%= link_to 'Log In', new_account_session_path, class: "btn btn-secondary mr-2 float-sm-right" %>
          <%= link_to 'Sign Up', new_account_registration_path, class: "btn btn-success float-sm-right" %>
      <% end %>
      <%# <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">

          <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }" %>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Settings</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <%= link_to profile_path(current_account), class: "nav-link" do %>
              <i data-feather="file-text"></i>
              My profile
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to edit_account_registration_path, class: "nav-link" do %>
              <i data-feather="settings"></i>
              Account Settings
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
  <%= link_to dashboard_path, class: "nav-link" do %>
  <i data-feather="home"></i>
    Dashboard <span class="sr-only">(current)</span>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <i data-feather="package"></i>
    Properties
  <% end %>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="calendar"></i>
    Viewings
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="users"></i>
    Contacts
  </a>
</li>